---
title: "Overview of flow based MCM"
author: "Kiize"
date: 2026-01-13
bibliography: refs.bib
---

## Problem

The MCMC method suffers from Critical Slowing Down, that is near the critical point physical simulations become really time-expensive. This is due to the local nature of the method and the high auto-correlations between sites near the critical point; the flow based MCMC [@Albergo_2019], on the other hand, samples a global configuration at every markovian time step, so it can generate improved auto-correlations and does not suffer from critical slowing down.

## Method and self-training

The paper proposes to use Normalizing Flows, which learn a map $f^{-1}$ ($f$ is called *flow*) to evaluate the target distribution $\tilde{p}_{f}$ and use it in the [[Metropolis algorithm]] to sample the true distribution of our system. The main advantage of this approach is the self-training, that is we do not need real data to train the model, but only the action of the system which enters in the (shifted) Kullback-Leibler (KL) divergence, that is the loss that we want to minimize.

## Real NVP flow

The main idea of this paper is enclosed in this diagram:
```{tikz}
\usepackage{tikz-cd}
\begin{document}
\begin{tikzcd}
z \arrow[dd] &  & \phi \arrow[ll, "f"'] \arrow[dd] \\
             &  &                                  \\
r \arrow[rr] &  & \tilde{p}_f                     
\end{tikzcd}
\end{document}
```
where $z$ are samples drawn from a simple (prior) distribution $r$: then $f^{-1}$ is a change of variables allowing us to sample $\phi$ according to the new distribution $\tilde{p}_{f}$, which is close to the effective, physical, distribution
$$
p(\phi) = \frac{e^{ -S(\phi) }}{Z}.
$$

Having said that, we construct the map $f$ using the real non-volume-preserving (NVP) flow approach, that is we costruct $f$ by composition of [[affine coupling]] layers $\{g_{i}\}$
$$
f(\phi) = g_{1} \circ g_{2} \circ \dots g_{n}(\phi).
$$
